const express = require('express')
const router = express.Router()
const pool = require('../db/postgres')
const { authenticateToken } = require('../middleware/auth')
const { NodeSSH } = require('node-ssh')
const fs = require('fs')

router.use(authenticateToken)

// GET /api/acl - List semua ACL entries
router.get('/', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT * FROM acl_entries
      ORDER BY type ASC, ip_or_subnet ASC
    `)
    res.json(result.rows)
  } catch (err) {
    console.error('List ACL error:', err)
    res.status(500).json({ error: 'Failed to list ACL entries' })
  }
})

// POST /api/acl - Tambah entry baru
router.post('/', async (req, res) => {
  try {
    const { ip_or_subnet, description, type = 'whitelist' } = req.body
    if (!ip_or_subnet) {
      return res.status(400).json({ error: 'ip_or_subnet is required' })
    }

    const result = await pool.query(`
      INSERT INTO acl_entries (ip_or_subnet, description, type)
      VALUES ($1, $2, $3)
      RETURNING *
    `, [ip_or_subnet, description || null, type])

    res.status(201).json(result.rows[0])
  } catch (err) {
    console.error('Create ACL error:', err)
    res.status(500).json({ error: 'Failed to create ACL entry' })
  }
})

// PUT /api/acl/:id - Update entry
router.put('/:id', async (req, res) => {
  try {
    const { ip_or_subnet, description, type, enabled } = req.body
    const result = await pool.query(`
      UPDATE acl_entries
      SET ip_or_subnet = COALESCE($1, ip_or_subnet),
          description = COALESCE($2, description),
          type = COALESCE($3, type),
          enabled = COALESCE($4, enabled),
          updated_at = NOW()
      WHERE id = $5
      RETURNING *
    `, [ip_or_subnet, description, type, enabled, req.params.id])

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'ACL entry not found' })
    }

    res.json(result.rows[0])
  } catch (err) {
    console.error('Update ACL error:', err)
    res.status(500).json({ error: 'Failed to update ACL entry' })
  }
})

// DELETE /api/acl/:id - Hapus entry
router.delete('/:id', async (req, res) => {
  try {
    const result = await pool.query(`
      DELETE FROM acl_entries WHERE id = $1 RETURNING *
    `, [req.params.id])

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'ACL entry not found' })
    }

    res.json({ message: 'ACL entry deleted' })
  } catch (err) {
    console.error('Delete ACL error:', err)
    res.status(500).json({ error: 'Failed to delete ACL entry' })
  }
})

// PATCH /api/acl/:id/toggle - Toggle enable/disable
router.patch('/:id/toggle', async (req, res) => {
  try {
    const result = await pool.query(`
      UPDATE acl_entries
      SET enabled = NOT enabled, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [req.params.id])

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'ACL entry not found' })
    }

    res.json(result.rows[0])
  } catch (err) {
    console.error('Toggle ACL error:', err)
    res.status(500).json({ error: 'Failed to toggle ACL entry' })
  }
})

// GET /api/acl/export - Export sebagai format konfigurasi dnsdist
router.get('/export', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT ip_or_subnet FROM acl_entries
      WHERE enabled = true AND type = 'whitelist'
      ORDER BY ip_or_subnet ASC
    `)

    const ips = result.rows.map(r => `"${r.ip_or_subnet}"`)
    const config = `-- Generated by DashDNS on ${new Date().toISOString()}\n` +
      `setACL({${ips.join(', ')}})\n`

    res.type('text/plain').send(config)
  } catch (err) {
    console.error('Export ACL error:', err)
    res.status(500).json({ error: 'Failed to export ACL' })
  }
})

// Helper: ambil settings dari database
async function getSshSettings() {
  const result = await pool.query("SELECT key, value FROM settings WHERE key LIKE 'dnsdist_ssh_%'")
  const settings = {}
  result.rows.forEach(r => { settings[r.key] = r.value })
  // Auto-detect SSH key path jika tidak diset atau tidak ditemukan
  const keyPath = settings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'
  if (!fs.existsSync(keyPath)) {
    const alternatives = ['/root/.ssh/id_ed25519', '/root/.ssh/id_ecdsa', '/root/.ssh/id_rsa']
    for (const alt of alternatives) {
      if (fs.existsSync(alt)) { settings.dnsdist_ssh_key_path = alt; break }
    }
  }
  return settings
}

// Helper: baca config dnsdist via SSH
async function readDnsdistConfig(ssh, host, port, user, keyPath) {
  await ssh.connect({ host, port: parseInt(port || '22'), username: user, privateKeyPath: keyPath, readyTimeout: 10000 })
  const { stdout } = await ssh.execCommand('sudo cat /etc/dnsdist/dnsdist.conf')
  await ssh.dispose()
  return stdout
}

// Helper: deploy config ke dnsdist via SSH + reload + verifikasi
async function writeDnsdistConfig(ssh, host, port, user, keyPath, config, expectedIps) {
  await ssh.connect({ host, port: parseInt(port || '22'), username: user, privateKeyPath: keyPath, readyTimeout: 10000 })
  await ssh.execCommand(`sudo tee /etc/dnsdist/dnsdist.conf > /dev/null << 'DNSCONFIG'\n${config}\nDNSCONFIG`)
  await ssh.execCommand('sudo systemctl reload dnsdist || sudo kill -HUP $(pidof dnsdist)')

  // Tunggu 1 detik biar reload selesai
  await new Promise(r => setTimeout(r, 1000))

  // Verifikasi: baca config balik, pastikan setACL terpasang
  const verify = await ssh.execCommand('sudo cat /etc/dnsdist/dnsdist.conf')
  const hasExpected = expectedIps && expectedIps.every(ip => verify.stdout.includes(ip))

  // Verifikasi: cek apakah dnsdist masih berjalan
  const status = await ssh.execCommand('sudo systemctl is-active dnsdist || echo "not running"')
  const isActive = status.stdout.trim() === 'active'

  await ssh.dispose()

  if (!isActive) {
    throw new Error('dnsdist is not running after reload')
  }
  if (!hasExpected) {
    throw new Error('Config written but setACL entries not verified in file')
  }

  return { isActive, verified: true }
}

// POST /api/acl/deploy - Deploy ACL ke semua dnsdist server via SSH
router.post('/deploy', async (req, res) => {
  try {
    const sshSettings = await getSshSettings()
    const hosts = (sshSettings.dnsdist_ssh_host || '').split(',').map(h => h.trim()).filter(Boolean)
    const port = sshSettings.dnsdist_ssh_port || '22'
    const user = sshSettings.dnsdist_ssh_user || 'root'
    const keyPath = sshSettings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'

    if (hosts.length === 0) {
      return res.status(400).json({ error: 'SSH hosts not configured. Go to Settings first.' })
    }

    // Ambil semua enabled whitelist dari database
    const result = await pool.query(`
      SELECT ip_or_subnet FROM acl_entries
      WHERE enabled = true AND type = 'whitelist'
      ORDER BY ip_or_subnet ASC
    `)

    const ips = result.rows.map(r => r.ip_or_subnet)
    if (ips.length === 0) {
      return res.status(400).json({ error: 'No enabled whitelist entries to deploy' })
    }

    const aclIps = ips.map(ip => `  "${ip}"`)
    const deployResults = []

    for (const host of hosts) {
      const ssh = new NodeSSH()
      try {
        const config = await readDnsdistConfig(ssh, host, port, user, keyPath)
        let newConfig = config.replace(/^\s*setACL\(\{[\s\S]*?^\}\)\n?/m, '')
        newConfig = newConfig.trimEnd() + `\n\n-- ACL managed by DashDNS\nsetACL({\n${aclIps.join(',\n')}\n})\n`

        const writeSsh = new NodeSSH()
        await writeDnsdistConfig(writeSsh, host, port, user, keyPath, newConfig, ips)

        deployResults.push({ host, status: 'success' })
      } catch (err) {
        try { await ssh.dispose() } catch (_) {}
        let errorMsg = err.message
        if (err.message.includes('private key')) {
          errorMsg = 'SSH key not found. Generate: ssh-keygen -t rsa -b 4096, lalu copy ke Settings'
        }
        deployResults.push({ host, status: 'error', error: errorMsg })
      }
    }

    const ok = deployResults.filter(r => r.status === 'success').length

    res.json({
      status: ok === hosts.length ? 'success' : 'partial',
      message: `Deployed ${ips.length} ACL entries to ${ok}/${hosts.length} servers`,
      details: deployResults
    })

  } catch (err) {
    console.error('Deploy ACL error:', err)
    res.status(500).json({ error: `Deploy failed: ${err.message}` })
  }
})

// POST /api/acl/sync - Sync ACL dari konfigurasi dnsdist ke database
router.post('/sync', async (req, res) => {
  try {
    const sshSettings = await getSshSettings()
    const hosts = (sshSettings.dnsdist_ssh_host || '').split(',').map(h => h.trim()).filter(Boolean)
    const port = sshSettings.dnsdist_ssh_port || '22'
    const user = sshSettings.dnsdist_ssh_user || 'root'
    const keyPath = sshSettings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'

    if (hosts.length === 0) {
      return res.status(400).json({ error: 'SSH hosts not configured. Go to Settings first.' })
    }

    const allIps = new Set()
    const syncResults = []

    for (const host of hosts) {
      const ssh = new NodeSSH()
      try {
        const config = await readDnsdistConfig(ssh, host, port, user, keyPath)

        // Parse semua IP/subnet dari setACL block
        const aclMatch = config.match(/setACL\(\{([\s\S]*?)\}\)/)
        if (aclMatch) {
          const ips = aclMatch[1].match(/"([^"]+)"/g) || []
          ips.forEach(ip => {
            const clean = ip.replace(/"/g, '').trim()
            if (clean) allIps.add(clean)
          })
        }

        await ssh.dispose()
        syncResults.push({ host, status: 'success', count: allIps.size })
      } catch (err) {
        try { await ssh.dispose() } catch (_) {}
        syncResults.push({ host, status: 'error', error: err.message })
      }
    }

    if (allIps.size === 0) {
      return res.json({ status: 'success', message: 'No ACL entries found in dnsdist config', added: 0, details: syncResults })
    }

    // Insert ke database, skip yang sudah ada
    let added = 0
    for (const ip of allIps) {
      const existing = await pool.query(`SELECT id FROM acl_entries WHERE ip_or_subnet = $1`, [ip])
      if (existing.rows.length === 0) {
        await pool.query(`
          INSERT INTO acl_entries (ip_or_subnet, description, type)
          VALUES ($1, 'Synced from dnsdist', 'whitelist')
        `, [ip])
        added++
      }
    }

    res.json({
      status: 'success',
      message: `Synced ${added} ACL entries from ${hosts.length} dnsdist server(s)`,
      added,
      details: syncResults
    })

  } catch (err) {
    console.error('Sync ACL error:', err)
    res.status(500).json({ error: `Sync failed: ${err.message}` })
  }
})

module.exports = router
