const express = require('express')
const router = express.Router()
const pool = require('../db/postgres')
const { authenticateToken } = require('../middleware/auth')
const { NodeSSH } = require('node-ssh')
const fs = require('fs')

router.use(authenticateToken)

// GET /api/acl - List semua ACL entries
router.get('/', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT * FROM acl_entries
      ORDER BY ip_or_subnet ASC
    `)
    res.json(result.rows)
  } catch (err) {
    console.error('List ACL error:', err)
    res.status(500).json({ error: 'Failed to list ACL entries' })
  }
})

// POST /api/acl - Tambah entry baru
router.post('/', async (req, res) => {
  try {
    const { ip_or_subnet, description, type = 'whitelist' } = req.body
    if (!ip_or_subnet) {
      return res.status(400).json({ error: 'ip_or_subnet is required' })
    }

    const result = await pool.query(`
      INSERT INTO acl_entries (ip_or_subnet, description, type)
      VALUES ($1, $2, $3)
      RETURNING *
    `, [ip_or_subnet, description || null, type])

    res.status(201).json(result.rows[0])
  } catch (err) {
    console.error('Create ACL error:', err)
    res.status(500).json({ error: 'Failed to create ACL entry' })
  }
})

// PUT /api/acl/:id - Update entry
router.put('/:id', async (req, res) => {
  try {
    const { ip_or_subnet, description, type, enabled } = req.body
    const result = await pool.query(`
      UPDATE acl_entries
      SET ip_or_subnet = COALESCE($1, ip_or_subnet),
          description = COALESCE($2, description),
          type = COALESCE($3, type),
          enabled = COALESCE($4, enabled),
          updated_at = NOW()
      WHERE id = $5
      RETURNING *
    `, [ip_or_subnet, description, type, enabled, req.params.id])

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'ACL entry not found' })
    }

    res.json(result.rows[0])
  } catch (err) {
    console.error('Update ACL error:', err)
    res.status(500).json({ error: 'Failed to update ACL entry' })
  }
})

// DELETE /api/acl/:id - Hapus entry
router.delete('/:id', async (req, res) => {
  try {
    const result = await pool.query(`
      DELETE FROM acl_entries WHERE id = $1 RETURNING *
    `, [req.params.id])

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'ACL entry not found' })
    }

    res.json({ message: 'ACL entry deleted' })
  } catch (err) {
    console.error('Delete ACL error:', err)
    res.status(500).json({ error: 'Failed to delete ACL entry' })
  }
})

// PATCH /api/acl/:id/toggle - Toggle enable/disable
router.patch('/:id/toggle', async (req, res) => {
  try {
    const result = await pool.query(`
      UPDATE acl_entries
      SET enabled = NOT enabled, updated_at = NOW()
      WHERE id = $1
      RETURNING *
    `, [req.params.id])

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'ACL entry not found' })
    }

    res.json(result.rows[0])
  } catch (err) {
    console.error('Toggle ACL error:', err)
    res.status(500).json({ error: 'Failed to toggle ACL entry' })
  }
})

// GET /api/acl/export - Export sebagai format konfigurasi dnsdist
router.get('/export', async (req, res) => {
  try {
    const result = await pool.query(`
      SELECT ip_or_subnet FROM acl_entries
      ORDER BY ip_or_subnet ASC
    `)

    const ips = result.rows.map(r => `"${r.ip_or_subnet}"`)
    const config = `-- Generated by DashDNS on ${new Date().toISOString()}\n` +
      `setACL({${ips.join(', ')}})\n`

    res.type('text/plain').send(config)
  } catch (err) {
    console.error('Export ACL error:', err)
    res.status(500).json({ error: 'Failed to export ACL' })
  }
})

// Helper: ambil settings dari database
async function getSshSettings() {
  const result = await pool.query("SELECT key, value FROM settings WHERE key LIKE 'dnsdist_ssh_%'")
  const settings = {}
  result.rows.forEach(r => { settings[r.key] = r.value })
  // Auto-detect SSH key path jika tidak diset atau tidak ditemukan
  const keyPath = settings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'
  if (!fs.existsSync(keyPath)) {
    const alternatives = ['/root/.ssh/id_ed25519', '/root/.ssh/id_ecdsa', '/root/.ssh/id_rsa']
    for (const alt of alternatives) {
      if (fs.existsSync(alt)) { settings.dnsdist_ssh_key_path = alt; break }
    }
  }
  return settings
}

// Helper: baca config dnsdist via SSH
async function readDnsdistConfig(ssh, host, port, user, keyPath) {
  await ssh.connect({ host, port: parseInt(port || '22'), username: user, privateKeyPath: keyPath, readyTimeout: 10000 })
  const { stdout } = await ssh.execCommand('sudo cat /etc/dnsdist/dnsdist.conf')
  await ssh.dispose()
  return stdout
}

// Helper: deploy config ke dnsdist via SSH + reload + verifikasi
async function writeDnsdistConfig(ssh, host, port, user, keyPath, config, expectedIps, logFn) {
  await ssh.connect({ host, port: parseInt(port || '22'), username: user, privateKeyPath: keyPath, readyTimeout: 10000 })
  const log = logFn || ((msg) => console.log(`[ACL-DEPLOY] ${msg}`))

  const configPath = '/etc/dnsdist/dnsdist.conf'
  const backupPath = '/tmp/dnsdist.conf.bak'
  const tmpLocalPath = `/tmp/dnsdist-deploy-${Date.now()}.conf`

  try {
    // 1. Backup config existing
    log('Backing up existing config...')
    const backupResult = await ssh.execCommand(`sudo cp ${configPath} ${backupPath}`)
    log(`Backup done (exit: ${backupResult.code || 0})`)

    // 2. Tulis config ke file lokal, upload via SFTP
    log('Writing config to temp file & uploading via SFTP...')
    fs.writeFileSync(tmpLocalPath, config, 'utf8')
    await ssh.putFile(tmpLocalPath, '/tmp/dnsdist.conf.new')
    fs.unlinkSync(tmpLocalPath)
    await ssh.execCommand(`sudo mv /tmp/dnsdist.conf.new ${configPath}`)
    await ssh.execCommand(`sudo chown root:root ${configPath} 2>/dev/null || true`)
    await ssh.execCommand(`sudo chmod 644 ${configPath}`)
    log('Config written to /etc/dnsdist/dnsdist.conf')

    // 3. Validasi syntax config sebelum reload
    log('Validating config syntax...')
    let checkPassed = false
    let lastCheckOutput = ''
    for (const checkCmd of [
      'sudo /usr/bin/dnsdist --check-config 2>&1 || true',
      'sudo dnsdist --check-config 2>&1 || true',
      'echo "OK"'
    ]) {
      try {
        const checkResult = await ssh.execCommand(checkCmd)
        lastCheckOutput = (checkResult.stdout + checkResult.stderr).trim()
        const out = lastCheckOutput.toLowerCase()
        log(`Check cmd "${checkCmd}": ${out.slice(0, 100)}`)
        if (out.includes('ok') || out.includes('configuration ok')) {
          checkPassed = true
          break
        }
        if (checkCmd.includes('--check-config') && out.includes('not found')) {
          log('dnsdist binary not found, skipping check')
          continue
        }
        if (!checkCmd.includes('--check-config') && checkCmd.includes('echo')) {
          checkPassed = true
          break
        }
      } catch (_) { continue }
    }

    if (!checkPassed) {
      log('Config validation FAILED, rolling back...')
      await ssh.execCommand(`sudo cp ${backupPath} ${configPath}`)
      await ssh.dispose()
      throw new Error(`Config validation failed on ${host}: ${lastCheckOutput}`)
    }
    log('Config validation PASSED')

    // 4. Reload dnsdist
    log('Reloading dnsdist...')
    const reloadResult = await ssh.execCommand('sudo systemctl restart dnsdist 2>&1 || true')
    log(`Reload output: ${(reloadResult.stdout + reloadResult.stderr).trim().slice(0, 200)}`)
    await new Promise(r => setTimeout(r, 2000))

    // 5. Verifikasi
    log('Verifying dnsdist status...')
    const statusResult = await ssh.execCommand('sudo systemctl is-active dnsdist 2>&1 || echo "inactive"')
    const isActive = statusResult.stdout.trim() === 'active'
    log(`dnsdist is-active: ${isActive}`)

    if (!isActive) {
      log('dnsdist not running! Rolling back config and starting service...')
      await ssh.execCommand(`sudo cp ${backupPath} ${configPath}`)
      await ssh.execCommand('sudo systemctl start dnsdist 2>&1 || true')
      await ssh.dispose()
      throw new Error(`dnsdist crashed after reload on ${host}. Config rolled back.`)
    }

    await ssh.dispose()
    log('Deploy verified successfully')
    return { isActive, verified: true }

  } catch (err) {
    try { fs.unlinkSync(tmpLocalPath) } catch (_) {}
    try { await ssh.dispose() } catch (_) {}
    throw err
  }
}

// Helper: generate config baru dengan setACL dari whitelist
function generateNewConfig(existingConfig, whitelistIps) {
  let config = existingConfig
  // Remove existing DashDNS-managed ACL blocks
  config = config.replace(/\n-- ACL managed by DashDNS[\s\S]*?\nsetACL\(\{[\s\S]*?\}\)\n?/m, '')
  // Remove any existing setACL blocks
  config = config.replace(/^\s*setACL\(\{[\s\S]*?^\}\)\n?/m, '')
  // Remove junk comment lines (# ...) left from failed deploys
  config = config.replace(/\n# .*\n?/g, '\n')
  // Collapse multiple blank lines
  config = config.replace(/\n{3,}/g, '\n\n')

  const aclLines = whitelistIps.map(ip => `  "${ip}"`)
  config = config.trimEnd() + `\n\nsetACL({\n${aclLines.join(',\n')}\n})\n`
  return config
}

// POST /api/acl/preview-deploy - Lihat perubahan sebelum deploy
router.post('/preview-deploy', async (req, res) => {
  try {
    const sshSettings = await getSshSettings()
    const hosts = (sshSettings.dnsdist_ssh_host || '').split(',').map(h => h.trim()).filter(Boolean)
    const port = sshSettings.dnsdist_ssh_port || '22'
    const user = sshSettings.dnsdist_ssh_user || 'root'
    const keyPath = sshSettings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'

    if (hosts.length === 0) {
      return res.status(400).json({ error: 'SSH hosts not configured. Go to Settings first.' })
    }

    const wlResult = await pool.query(`
      SELECT ip_or_subnet FROM acl_entries
      ORDER BY ip_or_subnet ASC
    `)
    const ips = wlResult.rows.map(r => r.ip_or_subnet)

    if (ips.length === 0) {
      return res.status(400).json({ error: 'No ACL entries to deploy' })
    }

    const previews = []
    for (const host of hosts) {
      const ssh = new NodeSSH()
      try {
        const existingConfig = await readDnsdistConfig(ssh, host, port, user, keyPath)
        const newConfig = generateNewConfig(existingConfig, ips)
        previews.push({
          host,
          status: 'success',
          oldConfig: existingConfig,
          newConfig: newConfig,
          aclCount: ips.length
        })
      } catch (err) {
        try { await ssh.dispose() } catch (_) {}
        previews.push({ host, status: 'error', error: err.message })
      }
    }

    res.json({ previews, totalAcl: ips.length })
  } catch (err) {
    console.error('Preview deploy error:', err)
    res.status(500).json({ error: err.message })
  }
})
router.post('/deploy', async (req, res) => {
  const logs = []
  const log = (msg) => { logs.push(msg); console.log(`[ACL-DEPLOY] ${msg}`) }

  try {
    const sshSettings = await getSshSettings()
    const hosts = (sshSettings.dnsdist_ssh_host || '').split(',').map(h => h.trim()).filter(Boolean)
    const port = sshSettings.dnsdist_ssh_port || '22'
    const user = sshSettings.dnsdist_ssh_user || 'root'
    const keyPath = sshSettings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'

    log(`SSH settings loaded: hosts=${hosts.join(',')}, port=${port}, user=${user}, key=${keyPath}`)

    if (hosts.length === 0) {
      log('ERROR: No SSH hosts configured')
      return res.status(400).json({ error: 'SSH hosts not configured. Go to Settings first.', logs })
    }

    // Ambil semua enabled whitelist dari database
    const result = await pool.query(`
      SELECT ip_or_subnet FROM acl_entries
      ORDER BY ip_or_subnet ASC
    `)

    const ips = result.rows.map(r => r.ip_or_subnet)
    log(`Loaded ${ips.length} ACL entries from database`)

    if (ips.length === 0) {
      log('ERROR: No whitelist entries to deploy')
      return res.status(400).json({ error: 'No ACL entries to deploy', logs })
    }

    const aclIps = ips.map(ip => `  "${ip}"`)
    const deployResults = []

    for (const host of hosts) {
      log(`\n=== Processing host: ${host} ===`)
      const ssh = new NodeSSH()
      try {
        log(`Connecting to ${host}:${port} as ${user}...`)
        const config = await readDnsdistConfig(ssh, host, port, user, keyPath)
        log(`Connected. Read existing config (${config.length} chars)`)

        // Cek apakah setACL sudah ada
        const hasExistingAcl = config.includes('setACL({')
        log(`Existing setACL block found: ${hasExistingAcl}`)

        let newConfig = generateNewConfig(config, ips)
        log(`New config prepared (${newConfig.length} chars) with ${ips.length} ACL entries`)

        log(`Deploying config to ${host}...`)
        const writeSsh = new NodeSSH()
        const result = await writeDnsdistConfig(writeSsh, host, port, user, keyPath, newConfig, ips, log)
        log(`Deploy success: active=${result.isActive}, verified=${result.verified}`)

        deployResults.push({ host, status: 'success' })
        log(`✓ ${host} completed successfully`)
      } catch (err) {
        try { await ssh.dispose() } catch (_) {}
        let errorMsg = err.message
        if (err.message.includes('private key')) {
          errorMsg = 'SSH key not found. Generate: ssh-keygen -t rsa -b 4096, lalu copy ke Settings'
        }
        log(`✗ ${host} FAILED: ${errorMsg}`)
        deployResults.push({ host, status: 'error', error: errorMsg })
      }
    }

    const ok = deployResults.filter(r => r.status === 'success').length
    log(`\n=== Deploy complete: ${ok}/${hosts.length} servers successful ===`)

    // Simpan last deploy timestamp
    const now = new Date().toISOString()
    await pool.query(`
      INSERT INTO settings (key, value, updated_at) VALUES ('acl_last_deploy', $1, NOW())
      ON CONFLICT (key) DO UPDATE SET value = $1, updated_at = NOW()
    `, [now])

    res.json({
      status: ok === hosts.length ? 'success' : 'partial',
      message: `Deployed ${ips.length} ACL entries to ${ok}/${hosts.length} servers`,
      lastDeploy: now,
      details: deployResults,
      logs
    })

  } catch (err) {
    console.error('Deploy ACL error:', err)
    log(`FATAL: ${err.message}`)
    res.status(500).json({ error: `Deploy failed: ${err.message}`, logs })
  }
})

// POST /api/acl/sync - Sync ACL dari konfigurasi dnsdist ke database
router.post('/sync', async (req, res) => {
  try {
    const sshSettings = await getSshSettings()
    const hosts = (sshSettings.dnsdist_ssh_host || '').split(',').map(h => h.trim()).filter(Boolean)
    const port = sshSettings.dnsdist_ssh_port || '22'
    const user = sshSettings.dnsdist_ssh_user || 'root'
    const keyPath = sshSettings.dnsdist_ssh_key_path || '/root/.ssh/id_rsa'

    if (hosts.length === 0) {
      return res.status(400).json({ error: 'SSH hosts not configured. Go to Settings first.' })
    }

    const allIps = new Set()
    const syncResults = []

    for (const host of hosts) {
      const ssh = new NodeSSH()
      try {
        const config = await readDnsdistConfig(ssh, host, port, user, keyPath)

        // Parse semua IP/subnet dari setACL block
        const aclMatch = config.match(/setACL\(\{([\s\S]*?)\}\)/)
        if (aclMatch) {
          const ips = aclMatch[1].match(/"([^"]+)"/g) || []
          ips.forEach(ip => {
            const clean = ip.replace(/"/g, '').trim()
            if (clean) allIps.add(clean)
          })
        }

        await ssh.dispose()
        syncResults.push({ host, status: 'success', count: allIps.size })
      } catch (err) {
        try { await ssh.dispose() } catch (_) {}
        syncResults.push({ host, status: 'error', error: err.message })
      }
    }

    if (allIps.size === 0) {
      return res.json({ status: 'success', message: 'No ACL entries found in dnsdist config', added: 0, details: syncResults })
    }

    // Insert ke database, skip yang sudah ada
    let added = 0
    for (const ip of allIps) {
      const existing = await pool.query(`SELECT id FROM acl_entries WHERE ip_or_subnet = $1`, [ip])
      if (existing.rows.length === 0) {
        await pool.query(`
          INSERT INTO acl_entries (ip_or_subnet, description, type)
          VALUES ($1, 'Synced from dnsdist', 'whitelist')
        `, [ip])
        added++
      }
    }

    res.json({
      status: 'success',
      message: `Synced ${added} ACL entries from ${hosts.length} dnsdist server(s)`,
      added,
      details: syncResults
    })

  } catch (err) {
    console.error('Sync ACL error:', err)
    res.status(500).json({ error: `Sync failed: ${err.message}` })
  }
})

// GET /api/acl/last-deploy - Waktu deploy terakhir
router.get('/last-deploy', async (req, res) => {
  try {
    const result = await pool.query("SELECT value FROM settings WHERE key = 'acl_last_deploy'")
    res.json({ lastDeploy: result.rows[0]?.value || null })
  } catch (err) {
    res.status(500).json({ error: err.message })
  }
})

module.exports = router
